table 'bcts_reporting bcts_performance_report_current_prev_ytd_issued_lic_volume'
	lineageTag: f021f7d2-7107-440d-bb6c-5a368df6d012

	measure 'Total Current YTD Licence Issued' = SUM('bcts_reporting bcts_performance_report_current_prev_ytd_issued_lic_volume'[Current YTD Licence Issued])
		formatString: #,0
		lineageTag: fbffd27e-e4dc-4d60-965f-f13fde4ef4a3

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'Total Previous YTD Licence Issued' = SUM('bcts_reporting bcts_performance_report_current_prev_ytd_issued_lic_volume'[Previous YTD Licence Issued])
		formatString: #,0
		lineageTag: fe5eae37-f6e1-41cb-b216-e96b3e8c0f13

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'Total Current YTD Licence Issued: Value Added' = SUM('bcts_reporting bcts_performance_report_current_prev_ytd_issued_lic_volume'[Current YTD Licence Issued: Value Added])
		formatString: #,0
		lineageTag: 773c52ee-6634-4a8a-bbfa-2df8d9ceff38

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'Total Previous YTD Licence Issued: Value Added' = SUM('bcts_reporting bcts_performance_report_current_prev_ytd_issued_lic_volume'[Previous YTD Licence Issued: Value Added])
		formatString: #,0
		lineageTag: 9c10ac6a-a29f-4bb0-bc64-8ff78fd25acc

		annotation PBI_FormatHint = {"isDecimal":true}

	column business_area_region_category
		dataType: string
		lineageTag: eab5883a-07a9-42e0-8963-c0fee9cece88
		summarizeBy: none
		sourceColumn: business_area_region_category
		sortByColumn: business_area_region_cat_number

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column business_area_region
		dataType: string
		lineageTag: 2140d66f-71b5-4efb-a8db-96e74b6683da
		summarizeBy: none
		sourceColumn: business_area_region

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column business_area
		dataType: string
		lineageTag: 967b013b-0be3-4c2f-891c-804cc93eeeac
		summarizeBy: none
		sourceColumn: business_area

		annotation SummarizationSetBy = Automatic

	column 'Current YTD Licence Issued'
		dataType: double
		lineageTag: 57d86d5d-3397-46a6-94ff-8da2ea922de0
		summarizeBy: sum
		sourceColumn: Current YTD Licence Issued

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Current YTD Licence Issued: Value Added'
		dataType: double
		lineageTag: c3f8f554-93f5-46ee-822f-8d529bb141b3
		summarizeBy: sum
		sourceColumn: Current YTD Licence Issued: Value Added

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Previous YTD Licence Issued'
		dataType: double
		lineageTag: 76357424-0ba7-43ad-8ca9-7872e2a72002
		summarizeBy: sum
		sourceColumn: Previous YTD Licence Issued

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Previous YTD Licence Issued: Value Added'
		dataType: double
		lineageTag: f620f504-e828-4393-93c9-27f50140d9ec
		summarizeBy: sum
		sourceColumn: Previous YTD Licence Issued: Value Added

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Current YTD Licence Issued: Other'
		dataType: double
		lineageTag: b8d459b9-1a5d-45c8-9291-78b7d43ab866
		summarizeBy: sum
		sourceColumn: Current YTD Licence Issued: Other

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Previous YTD Licence Issued: Other'
		dataType: double
		lineageTag: de1bcb94-ae9c-440f-8562-b8766f7bf1fc
		summarizeBy: sum
		sourceColumn: Previous YTD Licence Issued: Other

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column business_area_region_cat_number =
			
			SWITCH(
			    TRUE(),
			    'bcts_reporting bcts_performance_report_current_prev_ytd_issued_lic_volume'[business_area_region] IN { "North Interior", "South Interior" }, 1,
			    2
			)
		formatString: 0
		lineageTag: 9fec8286-39a8-4596-96dc-2ba5862c4339
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column y_max_business_area
		dataType: double
		lineageTag: 74e4412e-7ea5-4f03-8c28-6098207fdbb7
		summarizeBy: sum
		sourceColumn: y_max_business_area

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	hierarchy 'business_area_region_category Hierarchy'
		lineageTag: 513b1ab7-b875-44f2-a896-e03d520b35c1

		level 'Business Area'
			lineageTag: 4928ba37-318b-4f6c-8baf-d5d1765829ee
			column: business_area_region_category

		level business_area_region
			lineageTag: 2527685f-b8b9-433b-aad4-886da82fb7f3
			column: business_area_region

		level business_area
			lineageTag: bb63fe7f-4506-4b58-9dc2-daf31e9bdfda
			column: business_area

	partition 'bcts_reporting bcts_performance_report_current_prev_ytd_issued_lic_volume' = m
		mode: import
		source =
				let
				    Source = PostgreSQL.Database("existence.bcgov:5435", "odsprd"),
				    bcts_reporting_bcts_performance_report_current_prev_ytd_issued_lic_volume = Source{[Schema="bcts_reporting",Item="bcts_performance_report_current_prev_ytd_issued_lic_volume"]}[Data]
				in
				    bcts_reporting_bcts_performance_report_current_prev_ytd_issued_lic_volume

